language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose
  - cargo test --verbose --all-features
  - cargo run 16 5 3 0 1 --no-tui
  - cargo clippy --target wasm32-unknown-unknown --manifest-path web/Cargo.toml -- -D warnings
  - cargo build --target wasm32-unknown-unknown --manifest-path web/Cargo.toml --verbose
