language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
script:
  - cargo fmt --all -- --check
  - cargo clippy -- --deny=warnings
  - cargo build --verbose
  - cargo test --verbose --all-features
  - cd web; cargo build --target wasm32-unknown-unknown --verbose; cd ..
  - cd web; cargo test --target wasm32-unknown-unknown --verbose; cd ..