[package]
name = "rlifesrc"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

[dependencies]
combine = "3.8.1"
rand = { version = "0.6.5", features = ["stdweb"] }
yew = "0.6.0"
