name: Build and Deploy Web Version

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --all-features --manifest-path lib/Cargo.toml

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: target/deploy
      TARGET_PATH: target/wasm32-unknown-unknown/release
      RLIFESRC_PATH: rlifesrc/worker.js
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: latest

      - name: Run cargo build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --manifest-path web/Cargo.toml

      - name: Run wasm-bindgen
        run: |
          wasm-bindgen --target web --no-typescript --out-dir ${DEPLOY_PATH} ${TARGET_PATH}/main.wasm
          wasm-bindgen --target no-modules --no-typescript --out-dir ${DEPLOY_PATH} ${TARGET_PATH}/worker.wasm

      - name: Copy files
        run: cp -r web/static/* ${DEPLOY_PATH}

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ${{ env.DEPLOY_PATH }}
          single-commit: true
