name: Mirror this repo to Gitee

on:
  push:
    branches-ignore:
      - "dependabot/*"

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Mirror this repo to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/AlephAlpha
          dst: gitee/AlephAlpha
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "rlifesrc,rlifesrc-doc"
          force_update: true
